version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck        # Check for unchecked errors
    - govet           # Vet examines Go source code
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Advanced Go linter
    - unused          # Check for unused constants, variables, functions and types
    - revive          # General purpose linter
    - gosec           # Security problems
    - bodyclose       # Check HTTP response body is closed
    - noctx           # Check for sending http requests without context
    - sqlclosecheck   # Check SQL rows/statements are closed
    - errorlint       # Error wrapping checker
    - unparam         # Check for unused function parameters
    - wastedassign    # Find wasted assignment statements

  disable:
    - godot           # Disabled for Japanese comments
    - misspell        # Disabled for development efficiency
    - gofmt           # Disabled (IDE handles formatting)
    - goimports       # Disabled (IDE handles imports)
    - unconvert       # Disabled for development efficiency
    - gosimple        # Disabled for development efficiency
    - predeclared     # Disabled for development efficiency

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false
      - name: error-return
        disabled: false
      - name: error-naming
        disabled: false
      - name: if-return
        disabled: false
      - name: var-declaration
        disabled: false
      - name: unexported-return
        disabled: false

  gosec:
    excludes:
      - G404  # Use of weak random number generator (we use crypto/rand where needed)
    config:
      G101:
        pattern: "(?i)passwd|password|token|secret"

issues:
  exclude:
    - path: vendor
    - path: .github
  exclude-case-sensitive: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Exclude known issues in auto-generated code
    - path: internal/models/
      linters:
        - revive

    # Allow package comment to be on second line for main package
    - path: main\.go
      linters:
        - revive
      text: "package-comments"

  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
